### ISSUE TITLE
[Open3D WARNING] GLFW Error: X11: The DISPLAY environment variable is missing

### ISSUE THREAD

**Issue by Gearlessjoeee** [caoyunkang/CPMF#3]
when I want to run the code "python utils/generate_multi_view_dataset.py --dataset_path datasets/mvtec_3d_anomaly_detection --color-option UNIFORM --category bagel --save-dir result"
The error occurs ,Could you tell me how can I fix it? 
I try the method that set the environmnet variable "DISPLAY" as 1 ,but it fail.
Sincerely looking forward to your reply.

**Comment by YubingChan** [comment]
> 

Hi, I also have this problem, how do you solve it?

**Comment by YubingChan** [comment]
> > 
> 
> Hi, I also have this problem, how do you solve it?

change preprocess_dataset.sh the third line code "export DISPLAY=:0 " to "export DISPLAY=:1"

**Comment by Gearlessjoeee** [comment]
> > > 
> > 
> > 
> > Hi, I also have this problem, how do you solve it?
> 
> change preprocess_dataset.sh the third line code "export DISPLAY=:0 " to "export DISPLAY=:1"

My issue is that there is no monitor on the server, so I need to use X11 forwarding to establish a connection with the server and display the results on my local screen.

**Comment by YubingChan** [comment]
> > > > 
> > > 
> > > 
> > > Hi, I also have this problem, how do you solve it?
> > 
> > 
> > change preprocess_dataset.sh the third line code "export DISPLAY=:0 " to "export DISPLAY=:1"
> 
> My issue is that there is no monitor on the server, so I need to use X11 forwarding to establish a connection with the server and display the results on my local screen.
[here](https://github.com/caoyunkang/CPMF/blob/9a2b0d6f5402ed1f33120254b09b84a77e0126e5/preprocess_dataset.sh#L10)

**Comment by answer-miao** [comment]
> > > > 
> > > 
> > > 
> > > 嗨，我也有这个问题，你们如何解决呢？
> > 
> > 
> > 将第三行代码“export DISPLAY=：0”preprocess_dataset.sh更改为“export DISPLAY=：1”
> 
> 我的问题是服务器上没有显示器，所以我需要使用 X11 转发与服务器建立连接并将结果显示在我的本地屏幕上。

您好，请问您的问题是怎么解决的呀？
