### ISSUE TITLE
How to get qualitative results??

### ISSUE THREAD

**Issue by leo19910821** [caoyunkang/CPMF#5]
Can you please explain how to get the qualitative results or anomaly maps for test images?

**Comment by caoyunkang** [comment]
hi, by training ``python run_exp.py``, you could automatically get the qualitative results.

**Comment by leo19910821** [comment]
Thanks for your reply. However, after completing the run_exp.py it creates the results csv file but the following 
images/UNIFORM_resnet18_27_fpfh  , images/UNIFORM_resnet18_27 folders are empty.. Can you please let me know what I am doing wrong?

**Comment by caoyunkang** [comment]
hi, you can run `python main.py --draw True` to get the results.

**Comment by leo19910821** [comment]
Thanks...It worked
