### ISSUE TITLE
Evaluation Results on Eyecandies Dataset

### ISSUE THREAD

**Issue by zhiqing0205** [caoyunkang/CPMF#6]
I have conducted an evaluation of your model on a new dataset, Eyecandies. I deeply appreciate the valuable contribution you have made. Below are the detailed evaluation results:
### config
```
n_views: 27
no_fpfh: False
use_rgb: False
exp_name: UNIFORM_resnet18_27_fpfh
backbone: resnet18
```

|       |   CandyCane |   ChocolateCookie |   ChocolatePraline |   Confetto |   GummyBear |   HazelnutTruffle |   LicoriceSandwich |   Lollipop |   Marshmallow |   PeppermintCandy |   average |
|:------|------------:|------------------:|-------------------:|-----------:|------------:|------------------:|-------------------:|-----------:|--------------:|------------------:|----------:|
| I-AUROC |       77.28 |             79.52 |              75.04 |      84.64 |       74.04 |             58.40 |              74.56 |      81.99 |         71.04 |             81.28 |     75.779 |
| P-AUROC |       98.72 |             93.09 |              89.93 |      95.04 |       90.09 |             86.86 |              92.81 |      98.39 |         90.51 |             92.65 |     92.809 |
| AUPRO |       94.07 |             75.61 |              58.44 |      79.53 |       72.84 |             56.14 |              67.91 |      90.83 |         69.60 |             78.38 |     74.335 |

These results highlight the strengths and areas for improvement in your model when applied to the Eyecandies dataset. Your work has significantly contributed to advancing the understanding and performance of models in this domain.

Thank you once again for your hard work and dedication to this project.

**Comment by caoyunkang** [comment]
@zhiqing0205 Hi, thank you so much! We have incorporated your evaluation results in our repo.

**Comment by zhiqing0205** [comment]
You are welcome! It’s my honor to be a part of this amazing project!

**Comment by zacharyb02** [comment]
@zhiqing0205 Hello, Can you please provide the code used to calculate the evaluation results for Eyecandies dataset ?
